name: uni_mix

task_name: mix

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [9]
      type: low_dimx
    sparse_actions:
      shape: [4]
      type: low_dimx
  action:
    shape: [4]

env_runner: null


dataset:
  _target_: diffusion_policy_3d.dataset.uni_dataset.UniDataset
  zarr_path: /data1/lxy-24/Data/metaworld/WhiteScale___GeneralizedDP3/data
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 100000

